targets:
  $default:
    builders:
#      freezed:
#        enabled: True
#        generate_for:
#          - lib/model/**
#

      json_serializable:
        enabled: True
        generate_for:
          - lib/src/model/**
        options:
          any_map: true
          checked: true
          ignore_unannotated: true
          include_if_null: false
