// Event messages, no payload
const String STORYBOARD_RUNNER_COMPLETE = "STORYBOARD_RUNNER_COMPLETE";
const String BASE_BRANCH_UPDATED = "BASE_BRANCH_UPDATED";
const String CLOSE_STORYBOARD = "Window.closing";

// Event Key
const String STORYBOARD_EVENT_KEY = "[STORYBOARD_EVENT]";

// Environment variables key
const String STORYBOARD_FEATURE_BRANCH_NAME = "STORYBOARD_FEATURE_BRANCH_NAME";
const String STORYBOARD_BASE_BRANCH_NAME = "STORYBOARD_BASE_BRANCH_NAME";
